import Head from 'next/head'
import styles from './index.module.css'
import { useState, useEffect } from 'react'

import { Todo } from '../types/Todo'

export default function Home() {

  const [todos, setTodos] = useState([] as Todo[]);
  const [todo, setTodo] = useState('')
  const [editItemId, setEditItemId] = useState('')
  const [editItemTitle, setEditItemTitle] = useState('')

  async function fetchTodos() {
    let res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/todos`)
    res = await res.json();
    setTodos(res as unknown as Todo[])
  }

  useEffect(() => {
    fetchTodos()
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Todos App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          To Do List
        </h1>
        {todos.map(item => <div className={styles.item} key={item._id}>

          {
            editItemId !== item._id &&
            <>
              {item.title}
              <button onClick={() => {
                setEditItemId(item._id)
                setEditItemTitle(item.title)
              }}>edit</button>
              <button onClick={async () => {
                await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/remove`, {
                  method: 'DELETE',
                  body: JSON.stringify({ _id: item._id })
                })
                await fetchTodos()

              }}>remove</button>
            </>
          }
          {
            editItemId === item._id && <div className={styles.editItem}>
              <input
                type='text'
                value={editItemTitle}
                onChange={e => {
                  setEditItemId(item._id)
                  setEditItemTitle(e.target.value)
                }}
              />
              <button onClick={async () => {
                await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/update`, {
                  method: 'PUT',
                  body: JSON.stringify({ title: editItemTitle, _id: editItemId })
                })
                await fetchTodos()
                setEditItemId('')
                setEditItemTitle('')
              }}
              >save</button>
              <button onClick={() => {
                setEditItemId('')
                setEditItemTitle('')
              }}>cancel</button>
            </div>
          }

        </div>)}

        <div className={styles.addTodo} >
          <input type='text' value={todo} onChange={e => setTodo(e.target.value)} />
          <button onClick={async () => {
            await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/new`, {
              method: 'POST',
              body: JSON.stringify({ title: todo })
            })
            setTodo('')
            await fetchTodos()

          }}>add</button>
        </div>
      </main>
    </div>
  )
}
